#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in Modulefile
 modulefile

mod "java",
    :git => "https://github.com/cakesolutions/puppet-java.git"
    
